apiVersion: apps/v1
kind: Deployment
metadata:
  name: serwis-panel
  namespace: lotnisko-projekt
spec:
  replicas: 5
  selector:
    matchLabels:
      app: serwis-panel
  template:
    metadata:
      labels:
        app: serwis-panel
    spec:
      containers:
      - name: serwis-panel
        image: kacperklimas10/serwis_panel:latest
        env:
          - name: SERVER_PORT
            value: "8082"
          - name: SPRING_DATASOURCE_URL
#            value: "jdbc:mysql://172.20.10.5:3306/lotnisko_baza"
            value: "jdbc:mysql://192.168.1.15:3306/lotnisko_baza"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "haslo"
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: "none"
          - name: TOKEN_SERVICE_URL
            value: "http://serwis-logowania:8081"
        ports:
        - containerPort: 8082