apiVersion: apps/v1
kind: Deployment
metadata:
  name: serwis-logowania
  namespace: lotnisko-projekt
spec:
  replicas: 5
  selector:
    matchLabels:
      app: serwis-logowania
  template:
    metadata:
      labels:
        app: serwis-logowania
    spec:
      containers:
      - name: serwis-logowania
        image: kacperklimas10/serwis_logowania:latest
        env:
          - name: SERVER_PORT
            value: "8081"
          - name: SPRING_DATASOURCE_URL
#            value: "jdbc:mysql://172.20.10.5:3306/lotnisko_baza"
            value: "jdbc:mysql://192.168.1.15:3306/lotnisko_baza"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "haslo"
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: "none"
        ports:
        - containerPort: 8081