name: lotnisko_projekt
services:
  serwis-logowania:
    container_name: serwis_logowania
    image: kacperklimas10/serwis_logowania:dev
    build:
      context: ./serwis_logowania
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lotnisko_baza
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: haslo
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - my-network
      - backend
    ports:
      - "8081:8081"

  serwis-panel:
    container_name: serwis_panel
    image: kacperklimas10/serwis_panel:dev
    build:
      context: ./serwis_panel
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lotnisko_baza
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: haslo
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      TOKEN_SERVICE_URL: http://serwis-logowania:8081
    networks:
      - my-network
      - backend
    ports:
      - "8082:8082"

  serwis-frontend:
    container_name: serwis_frontend
    image: kacperklimas10/serwis_frontend:dev
    build:
      context: ./frontend
    networks:
      - my-network
    ports:
      - "81:80"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - my-network
      - backend
    ports:
      - "6969:80"

  db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "haslo"
      MYSQL_DATABASE: "lotnisko_baza"
    networks:
      - backend
    volumes:
      - db-vol:/var/lib/mysql

networks:
  my-network:
  backend:
volumes:
  db-vol: