apiVersion: apps/v1
kind: Deployment
metadata:
  name: serwis-panel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serwis-panel
  template:
    metadata:
      labels:
        app: serwis-panel
    spec:
      containers:
      - name: serwis-panel
        image: kacperklimas10/serwis_panel:latest
        env:
          - name: SERVER_PORT
            value: "8082"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://192.168.8.254:3306/lotnisko_baza"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "haslo"
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: "none"
          - name: TOKEN_SERVICE_URL
            value: "http://serwis-logowania:8081"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: serwis-panel
spec:
  selector:
    app: serwis-panel
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082