apiVersion: apps/v1
kind: Deployment
metadata:
  name: serwis-logowania
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serwis-logowania
  template:
    metadata:
      labels:
        app: serwis-logowania
    spec:
      containers:
      - name: serwis-logowania
        image: kacperklimas10/serwis_logowania:latest
        env:
          - name: SERVER_PORT
            value: "8081"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://192.168.8.254:3306/lotnisko_baza"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "haslo"
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: "none"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: serwis-logowania
spec:
  selector:
    app: serwis-logowania
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081