apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
  namespace: serwis-db
spec:
  type: ClusterIP
  selector:
    app: db
    tier: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: phpmyadmin
      protocol: TCP
      port: 80
      targetPort: 80