apiVersion: apps/v1
kind: Deployment
metadata:
  name: serwis-panel
  namespace: serwis-panel
spec:
  replicas: 5
  selector:
    matchLabels:
      app: serwis-panel
  template:
    metadata:
      labels:
        app: serwis-panel
    spec:
      containers:
      - name: serwis-panel
        image: kacperklimas10/serwis_panel:latest
        imagePullPolicy: Always
        env:
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: serwis-panel-configmap
                key: SERVER_PORT
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: serwis-panel-secret
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: serwis-panel-secret
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: serwis-panel-secret
                key: SPRING_DATASOURCE_PASSWORD
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            valueFrom:
              configMapKeyRef:
                name: serwis-panel-configmap
                key: SPRING_JPA_HIBERNATE_DDL_AUTO
          - name:  TOKEN_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: serwis-panel-configmap
                key: TOKEN_SERVICE_URL
        ports:
        - containerPort: 8082
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false