apiVersion: v1
kind: Service
metadata:
  name: serwis-panel
  namespace: serwis-panel
spec:
  selector:
    app: serwis-panel
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: serwis-logowania-api
  namespace: serwis-panel
spec:
  type: ExternalName
  externalName: serwis-logowania.serwis-logowania.svc.cluster.local