apiVersion: apps/v1
kind: Deployment
metadata:
  name: serwis-frontend
  namespace: serwis-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serwis-frontend
  template:
    metadata:
      labels:
        app: serwis-frontend
    spec:
      containers:
        - name: serwis-frontend
          image: kacperklimas10/serwis_frontend:prod-multiarch
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false