name: lotnisko_projekt CI/CD
on:
  push:
    branches:
    - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build serwis_logowania with Maven Wrapper
      run: ./serwis_logowania/mvnw -f ./serwis_logowania/pom.xml clean install -DskipTests

    - name: Build serwis_panel with Maven Wrapper
      run: ./serwis_panel/mvnw -f ./serwis_panel/pom.xml clean install -DskipTests
    
    - name: Set up Docker environment
      uses: docker/setup-buildx-action@v1
      
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image and push serwis_logowania
      uses: docker/build-push-action@v2
      with:
        context: ./serwis_logowania
        file: ./serwis_logowania/Dockerfile
        push: true
        tags: kacperklimas10/serwis_logowania:latest

    - name: Build image and push serwis_panel
      uses: docker/build-push-action@v2
      with:
        context: ./serwis_panel
        file: ./serwis_panel/Dockerfile
        push: true
        tags: kacperklimas10/serwis_panel:latest

    - name: Build image and push serwis_frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: kacperklimas10/serwis_frontend:latest
